# test config mushra page, waveform, 5 conditions, no looping


testname: DE-AMPING MUSHRA
testId: mushra_DE-AMPING
bufferSize: 2048
stopOnErrors: false
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Welcome to the De-Amping mini listening test
      content: |
        PLEASE READ THE FOLLOWING: In this test, you will evaluate the quality of different models.
        You will listen to a reference DI signal (the undistorted version) and the output of several models.
        Your task is to compare each test sample to the clean reference and rate its quality on a scale from 0 to 100, where
        100 means the sample sounds identical to the clean reference (best quality).
        0 means the sample sounds very different from the clean reference (worst quality). The distorted audio is also provided in the conditions as an anchor.
        Please use headphones for this test.




    - type: mushra
      id: trial1
      name: Song 1 / 4
      content: 100 sounds identical to the reference (best quality), 0 is the worst
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/t1/17gte180_8RR_out for blood-DI_d_1.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/t1/run16_18gtd180_8RR_out for blood_d_1.wav
          C2: configs/resources/audio/t1/run46_18gtd180_8RR_out for blood_d_1.wav
          C3: configs/resources/audio/t1/run47_18gtd180_8RR_out for blood_d_1.wav
          C4: configs/resources/audio/t1/run50_18gtd180_8RR_out for blood_d_1.wav
          C5: configs/resources/audio/t1/18gtd180_8RR_out for blood_d_1.wav

    - type: finish
      name: Thank you for attending, please download your results file and send the .csv to me via skype chat.
      content: Have a nice day
      popupContent:
      showResults: true
      writeResults: true
