# test config mushra page, waveform, 5 conditions, no looping


testname: MUSHRA without looping DE-AMPING
testId: mushra_noloop_DE-AMPING
bufferSize: 2048
stopOnErrors: false
showButtonPreviousPage: true
remoteService: service/write.php


pages:

    - type: mushra
      id: trial1
      name: DE-AMPING TRIAL
      content: test description
      showWaveform: true
      enableLooping: false 
      reference: configs/resources/audio/DI_10.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/run46_Mesa_10.wav
          C2: configs/resources/audio/run50_Mesa_10.wav
          C3: configs/resources/audio/run47_Mesa_10.wav
          C4: configs/resources/audio/DI_10.wav

    - type: finish
      name: Thank you
      content: Thank you for attending
      popupContent: Your results were sent. Goodbye and have a nice day
      showResults: true
      writeResults: true
